import { AudioFx } from "@fx/components/audio-fx.js";
import { PageFx } from "@fx/components/page-fx.js";
import { ColumnFx } from "@fx/components/column-fx.js";
import { SectionFx } from "@fx/components/section-fx.js";
import { TextFx } from "@fx/components/text-fx.js";
import { HeadingFx } from "@fx/components/heading-fx.js";
import { ImageFx } from "@fx/components/image-fx.js?test";
import { LinkFx } from "@fx/components/link-fx.js";
import { VideoFx } from "@fx/components/video-fx.js";